theme: minima
title: Life Of A Computer Engineer
author: idiotic me
email: no@not.com
description: 
  Our Life is quite a tough one to live . Yet its the most interesting thing to be able to create new things just sitting in your room in pyjamas . In the begining you may face problems in learning
  But once you actually get into it , you enjoy it . I am at a stage where i am trying to fit into this developer community . I swear this is getting tougher . But i will not give up and keep trying . Its my curiosity (though i woke up a little too late) thats keeping me going . 
twitter_username: shhh
github_username:  nooo

show_excerpts: true # set to false to remove excerpts on the homepage
